version: '3'
services:
  # This is James' frontend service
  frontend:
    restart: always
    build: ./frontend
    ports: 
      - "80:8080"
    volumes:
      - ./frontend:/code
    depends_on:
      - db
      - backend
  # This is Alain's backend service
  backend:
    restart: always
    build: ./backend
    ports:
      - "8080:8080"
    volumes:
      - ~/.gradle:/root/.gradle
    depends_on:
      - db
  # This database service is only accessible within this set of services. The hostname is the same as the service: db
  db:
    build: ./db
    restart: always
